name: eceee
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/GoogleSans-Bold.ttf
        - asset: assets/GoogleSans-BoldItalic.ttf
        - asset: assets/GoogleSans-Italic.ttf
        - asset: assets/GoogleSans-Medium.ttf
        - asset: assets/GoogleSans-MediumItalic.ttf
        - asset: assets/GoogleSans-Regular.ttf

    - family: Proxima
      fonts:
        - asset: assets/Proxima Nova Font.otf