name: eceee
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  firebase_database: ^10.0.16

  flutter_svg: ^1.1.6
  http: ^0.13.3
  flutter_bloc: ^8.1.2
  cloud_firestore: ^4.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/Images&SVG/
    - assets/Icones/


  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/Police/GoogleSans-Bold.ttf
        - asset: assets/Police/GoogleSans-BoldItalic.ttf
        - asset: assets/Police/GoogleSans-Italic.ttf
        - asset: assets/Police/GoogleSans-Medium.ttf
        - asset: assets/Police/GoogleSans-MediumItalic.ttf
        - asset: assets/Police/GoogleSans-Regular.ttf

    - family: Proxima
      fonts:
        - asset: assets/Police/Proxima Nova Font.otf

