// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpZK6lqbIzQpxMvciheSWQMOn3HImrDVQ',
    appId: '1:441098010455:web:337008b8892230b2358812',
    messagingSenderId: '441098010455',
    projectId: 'fir-project-1e663',
    authDomain: 'fir-project-1e663.firebaseapp.com',
    storageBucket: 'fir-project-1e663.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsP2g-lctp0ot1tJtktRYMxePC-4rzFIA',
    appId: '1:441098010455:android:48b3824945e2f749358812',
    messagingSenderId: '441098010455',
    projectId: 'fir-project-1e663',
    storageBucket: 'fir-project-1e663.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU_Tb7G3ArU51_dr7Mmxv8OvNluLAkJH0',
    appId: '1:441098010455:ios:73b5770558e8261d358812',
    messagingSenderId: '441098010455',
    projectId: 'fir-project-1e663',
    storageBucket: 'fir-project-1e663.appspot.com',
    iosClientId: '441098010455-vhjte1gnbi7k6te22bkjknq6d14t1fgt.apps.googleusercontent.com',
    iosBundleId: 'com.example.eceee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU_Tb7G3ArU51_dr7Mmxv8OvNluLAkJH0',
    appId: '1:441098010455:ios:73b5770558e8261d358812',
    messagingSenderId: '441098010455',
    projectId: 'fir-project-1e663',
    storageBucket: 'fir-project-1e663.appspot.com',
    iosClientId: '441098010455-vhjte1gnbi7k6te22bkjknq6d14t1fgt.apps.googleusercontent.com',
    iosBundleId: 'com.example.eceee',
  );
}
